# Generated by Django 5.0.7 on 2024-11-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1_name", models.CharField(max_length=50)),
                ("player2_name", models.CharField(max_length=50)),
                ("board", models.JSONField(default=list)),
                ("active_player", models.CharField(max_length=50)),
                ("winner", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
